export type Language = 'en' | 'it' | 'fr';

const en = {
  nav: { rooms: 'Rooms', dining: 'Dining', amenities: 'Amenities', gallery: 'Gallery', about: 'About', contact: 'Contact', reserveNow: 'Reserve Now' },
  hero: { subtitle: 'Five-Star Luxury Hotel & Resort', description: 'Where timeless elegance meets modern luxury. Experience world-class hospitality, Michelin-star dining, and bespoke service in the heart of the Mediterranean.', bookStay: 'Book Your Stay', exploreRooms: 'Explore Rooms' },
  rooms: { label: 'Accommodations', title: 'Rooms & Suites', description: 'Each room is a sanctuary of refined taste, designed for guests who appreciate the extraordinary.', reserveRoom: 'Reserve This Room', perNight: '/night', guests: 'Guests', noRooms: 'No rooms available at the moment.' },
  footer: { tagline: 'Five-star luxury on the Mediterranean coast. Where timeless elegance meets modern sophistication.', quickLinks: 'Quick Links', guestServices: 'Guest Services', bookRoom: 'Book a Room', restaurantRes: 'Restaurant Reservation', contactUs: 'Contact Us', contactLabel: 'Contact', privacy: 'Privacy Policy', terms: 'Terms of Service', cookies: 'Cookie Policy', rights: '© 2026 Aurelia Grand. All rights reserved.' },
  booking: { title: 'Book Your Stay', subtitle: 'Select your room, dates, and complete your reservation.', backHome: 'Back to Home', selectRoom: 'Select Room', checkInDate: 'Check-in Date', checkOutDate: 'Check-out Date', selectDate: 'Select date', numGuests: 'Number of Guests', guest: 'Guest', guestsLabel: 'Guests', roomDates: 'Room & Dates', guestDetails: 'Guest Details', checkingAvail: 'Checking availability...', available: 'Available!', notAvailable: 'Not Available', notAvailableDesc: 'These dates are unavailable. Please try different dates.', continue: 'Continue to Guest Details', bookingSummary: 'Booking Summary', night: 'night', nights: 'nights', total: 'Total', fullName: 'Full Name', email: 'Email', phone: 'Phone', specialRequests: 'Special Requests', back: 'Back', submit: 'Submit Reservation', submitting: 'Submitting...', submitted: 'Reservation Submitted', submittedThank: 'Thank you! Your reservation has been received.', pendingNote: "Status: Pending — We'll confirm your booking within 24 hours.", returnHome: 'Return Home' },
  admin: {
    dashboard: 'Dashboard', reservations: 'Reservations', roomTypes: 'Room Types', availability: 'Availability', pricing: 'Pricing', staff: 'Staff', invoices: 'Invoices', settings: 'Settings', signOut: 'Sign Out', adminPanel: 'Admin Panel',
    save: 'Save', saving: 'Saving...', cancel: 'Cancel', edit: 'Edit', delete: 'Delete', create: 'Create', search: 'Search', actions: 'Actions', status: 'Status', noData: 'No data', confirm: 'Confirm', active: 'Active',
    loginTitle: 'Admin Portal', loginSubtitle: 'Sign in to manage your property', email: 'Email', password: 'Password', signIn: 'Sign In', signingIn: 'Signing in...',
    totalReservations: 'Total Reservations', pending: 'Pending', revenueMonth: 'Revenue (Month)', checkInsToday: 'Check-Ins Today', checkOutsToday: 'Check-Outs Today', occupancy: 'Occupancy', bookingsOverview: 'Bookings Overview', last6Months: 'Last 6 months', reservationStatus: 'Reservation Status', recentReservations: 'Recent Reservations', viewAll: 'View All', guestsOverview: 'Guests Overview', roomOccupancy: 'Room Occupancy', conflict: 'Conflict',
    upcomingArrivals: 'Upcoming Arrivals', upcomingDepartures: 'Upcoming Departures', revenueToday: 'Revenue Today', quickActions: 'Quick Actions', addGuest: 'Add Guest', unconfirmedAlert: 'Unconfirmed Reservations', pendingReservationsAlert: 'pending reservations need attention', bookingSourceBreakdown: 'Booking Sources', occupancyNext7Days: 'Occupancy Next 7 Days', todayTomorrow: 'Today & Tomorrow', website: 'Website', manual: 'Manual', direct: 'Direct', noPendingReservations: 'No pending reservations',
    searchGuests: 'Search guests...', allStatus: 'All Status', confirmed: 'Confirmed', cancelled: 'Cancelled', completed: 'Completed', newReservation: 'New Reservation', editReservation: 'Edit Reservation', reservationDetails: 'Reservation Details', code: 'Code', guest: 'Guest', room: 'Room', checkIn: 'Check-In', checkOut: 'Check-Out', guestName: 'Guest Name', guestEmail: 'Email', guestPhone: 'Phone', guests: 'Guests', totalPrice: 'Total Price', specialRequests: 'Special Requests', notes: 'Notes', createReservation: 'Create Reservation', creating: 'Creating...', markCompleted: 'Mark Completed', saveChanges: 'Save Changes', payment: 'Payment', source: 'Source', roomType: 'Room Type', selectRoom: 'Select room', noReservations: 'No reservations', noReservationsDesc: 'No reservations match your filters.',
    addRoomType: 'Add Room Type', editRoomType: 'Edit Room Type', newRoomType: 'New Room Type', roomName: 'Name', description: 'Description', basePrice: 'Base Price', weekendPrice: 'Weekend Price', maxGuests: 'Max Guests', availableUnits: 'Available Units', roomSize: 'Room Size', imageUrl: 'Image URL', amenitiesLabel: 'Amenities', showOnWebsite: 'Show on Website', showOnWebsiteDesc: 'Make this room visible on the public website', visibleOnWebsite: 'Visible on website', hiddenFromWebsite: 'Hidden from website', deleteRoomType: 'Delete this room type?', units: 'units', unit: 'unit', noRoomTypesTitle: 'No room types', noRoomTypesDesc: 'Add your first room type to get started.',
    selectRoomType: 'Select room type', blockDates: 'Block Dates', noRoomTypesAvail: 'No room types', noRoomTypesAvailDesc: 'Create room types first to manage availability.', clickToBlock: 'Click a date to block/unblock', blockedDates: 'Blocked Dates', noBlockedDates: 'No blocked dates for this room type.', blockDate: 'Block Date', date: 'Date', reason: 'Reason', reserved: 'Reserved', blocked: 'Blocked', availOverview: 'Room Availability Overview', free: 'Free', occupied: 'Occupied', totalUnits: 'Total Units', bookedUnits: 'Booked', freeUnits: 'Free',
    basePricing: 'Base Pricing', dateRangeOverrides: 'Date Range Overrides', addOverride: 'Add Override', noOverrides: 'No pricing overrides set.', startDate: 'Start Date', endDate: 'End Date', overridePrice: 'Override Price', labelOptional: 'Label (optional)', period: 'Period', label: 'Label', editPricing: 'Edit Pricing', updatePrice: 'Update Price',
    staffMembers: 'staff members', addStaff: 'Add Staff', editStaff: 'Edit Staff', staffName: 'Name', role: 'Role / Job Title', removeStaff: 'Remove this staff member?', updateStaff: 'Update Staff', noStaff: 'No staff', noStaffDesc: 'Add staff members to your directory.',
    createInvoice: 'Create Invoice', invoiceNumber: 'Invoice #', amount: 'Amount', reservation: 'Reservation', markSent: 'Mark Sent', markPaid: 'Mark Paid', download: 'Download PDF', sendEmail: 'Send Email', selectReservation: 'Select reservation', noInvoices: 'No invoices', noInvoicesDesc: 'Create your first invoice from a reservation.', invoiceDownloaded: 'Invoice downloaded', invoiceSent: 'Invoice sent', sendingEmail: 'Sending...',
    hotelInfo: 'Hotel Information', hotelName: 'Hotel Name', logoUrl: 'Logo URL', address: 'Address', phone: 'Phone', operations: 'Operations', currency: 'Currency', checkInTime: 'Check-In Time', checkOutTime: 'Check-Out Time', taxPercentage: 'Tax Percentage', policies: 'Policies', bookingPolicy: 'Booking Policy', cancellationPolicy: 'Cancellation Policy', language: 'Language', theme: 'Theme', light: 'Light', dark: 'Dark', system: 'System', settingsSaved: 'Settings saved', saveSettings: 'Save Settings', appearance: 'Appearance',
  },
};

const it: typeof en = {
  nav: { rooms: 'Camere', dining: 'Ristorazione', amenities: 'Servizi', gallery: 'Galleria', about: 'Chi Siamo', contact: 'Contatti', reserveNow: 'Prenota Ora' },
  hero: { subtitle: 'Hotel & Resort di Lusso a Cinque Stelle', description: "Dove l'eleganza senza tempo incontra il lusso moderno. Scopri un'ospitalità di classe mondiale, cucina stellata Michelin e servizio su misura nel cuore del Mediterraneo.", bookStay: 'Prenota il Tuo Soggiorno', exploreRooms: 'Scopri le Camere' },
  rooms: { label: 'Alloggi', title: 'Camere & Suite', description: 'Ogni camera è un santuario di gusto raffinato, progettato per ospiti che apprezzano lo straordinario.', reserveRoom: 'Prenota Questa Camera', perNight: '/notte', guests: 'Ospiti', noRooms: 'Nessuna camera disponibile al momento.' },
  footer: { tagline: "Lusso a cinque stelle sulla costa mediterranea. Dove l'eleganza senza tempo incontra la sofisticazione moderna.", quickLinks: 'Link Rapidi', guestServices: 'Servizi Ospiti', bookRoom: 'Prenota una Camera', restaurantRes: 'Prenotazione Ristorante', contactUs: 'Contattaci', contactLabel: 'Contatti', privacy: 'Informativa Privacy', terms: 'Termini di Servizio', cookies: 'Informativa Cookie', rights: '© 2026 Aurelia Grand. Tutti i diritti riservati.' },
  booking: { title: 'Prenota il Tuo Soggiorno', subtitle: 'Seleziona la camera, le date e completa la prenotazione.', backHome: 'Torna alla Home', selectRoom: 'Seleziona Camera', checkInDate: 'Data Check-in', checkOutDate: 'Data Check-out', selectDate: 'Seleziona data', numGuests: 'Numero Ospiti', guest: 'Ospite', guestsLabel: 'Ospiti', roomDates: 'Camera & Date', guestDetails: 'Dettagli Ospite', checkingAvail: 'Verifica disponibilità...', available: 'Disponibile!', notAvailable: 'Non Disponibile', notAvailableDesc: 'Queste date non sono disponibili. Prova date diverse.', continue: 'Continua ai Dettagli', bookingSummary: 'Riepilogo Prenotazione', night: 'notte', nights: 'notti', total: 'Totale', fullName: 'Nome Completo', email: 'Email', phone: 'Telefono', specialRequests: 'Richieste Speciali', back: 'Indietro', submit: 'Invia Prenotazione', submitting: 'Invio in corso...', submitted: 'Prenotazione Inviata', submittedThank: 'Grazie! La tua prenotazione è stata ricevuta.', pendingNote: 'Stato: In attesa — Confermeremo entro 24 ore.', returnHome: 'Torna alla Home' },
  admin: {
    dashboard: 'Pannello', reservations: 'Prenotazioni', roomTypes: 'Tipi di Camera', availability: 'Disponibilità', pricing: 'Prezzi', staff: 'Personale', invoices: 'Fatture', settings: 'Impostazioni', signOut: 'Esci', adminPanel: 'Pannello Admin',
    save: 'Salva', saving: 'Salvataggio...', cancel: 'Annulla', edit: 'Modifica', delete: 'Elimina', create: 'Crea', search: 'Cerca', actions: 'Azioni', status: 'Stato', noData: 'Nessun dato', confirm: 'Conferma', active: 'Attivo',
    loginTitle: 'Portale Admin', loginSubtitle: 'Accedi per gestire la tua struttura', email: 'Email', password: 'Password', signIn: 'Accedi', signingIn: 'Accesso in corso...',
    totalReservations: 'Prenotazioni Totali', pending: 'In Attesa', revenueMonth: 'Ricavi (Mese)', checkInsToday: 'Check-in Oggi', checkOutsToday: 'Check-out Oggi', occupancy: 'Occupazione', bookingsOverview: 'Panoramica Prenotazioni', last6Months: 'Ultimi 6 mesi', reservationStatus: 'Stato Prenotazioni', recentReservations: 'Prenotazioni Recenti', viewAll: 'Vedi Tutto', guestsOverview: 'Panoramica Ospiti', roomOccupancy: 'Occupazione Camere', conflict: 'Conflitto',
    upcomingArrivals: 'Arrivi Imminenti', upcomingDepartures: 'Partenze Imminenti', revenueToday: 'Ricavi Oggi', quickActions: 'Azioni Rapide', addGuest: 'Aggiungi Ospite', unconfirmedAlert: 'Prenotazioni Non Confermate', pendingReservationsAlert: 'prenotazioni in attesa richiedono attenzione', bookingSourceBreakdown: 'Fonti Prenotazione', occupancyNext7Days: 'Occupazione Prossimi 7 Giorni', todayTomorrow: 'Oggi e Domani', website: 'Sito Web', manual: 'Manuale', phone: 'Telefono', direct: 'Diretto', noPendingReservations: 'Nessuna prenotazione in attesa',
    searchGuests: 'Cerca ospiti...', allStatus: 'Tutti gli Stati', confirmed: 'Confermata', cancelled: 'Cancellata', completed: 'Completata', newReservation: 'Nuova Prenotazione', editReservation: 'Modifica Prenotazione', reservationDetails: 'Dettagli Prenotazione', code: 'Codice', guest: 'Ospite', room: 'Camera', checkIn: 'Check-In', checkOut: 'Check-Out', guestName: 'Nome Ospite', guestEmail: 'Email', guestPhone: 'Telefono', guests: 'Ospiti', totalPrice: 'Prezzo Totale', specialRequests: 'Richieste Speciali', notes: 'Note', createReservation: 'Crea Prenotazione', creating: 'Creazione...', markCompleted: 'Segna Completata', saveChanges: 'Salva Modifiche', payment: 'Pagamento', source: 'Fonte', roomType: 'Tipo Camera', selectRoom: 'Seleziona camera', noReservations: 'Nessuna prenotazione', noReservationsDesc: 'Nessuna prenotazione corrisponde ai filtri.',
    addRoomType: 'Aggiungi Tipo Camera', editRoomType: 'Modifica Tipo Camera', newRoomType: 'Nuovo Tipo Camera', roomName: 'Nome', description: 'Descrizione', basePrice: 'Prezzo Base', weekendPrice: 'Prezzo Weekend', maxGuests: 'Ospiti Max', availableUnits: 'Unità Disponibili', roomSize: 'Dimensione', imageUrl: 'URL Immagine', amenitiesLabel: 'Servizi', showOnWebsite: 'Mostra sul Sito', showOnWebsiteDesc: 'Rendi questa camera visibile sul sito pubblico', visibleOnWebsite: 'Visibile sul sito', hiddenFromWebsite: 'Nascosta dal sito', deleteRoomType: 'Eliminare questo tipo di camera?', units: 'unità', unit: 'unità', noRoomTypesTitle: 'Nessun tipo di camera', noRoomTypesDesc: 'Aggiungi il primo tipo di camera per iniziare.',
    selectRoomType: 'Seleziona tipo camera', blockDates: 'Blocca Date', noRoomTypesAvail: 'Nessun tipo di camera', noRoomTypesAvailDesc: 'Crea prima i tipi di camera per gestire la disponibilità.', clickToBlock: 'Clicca una data per bloccare/sbloccare', blockedDates: 'Date Bloccate', noBlockedDates: 'Nessuna data bloccata per questo tipo di camera.', blockDate: 'Blocca Data', date: 'Data', reason: 'Motivo', reserved: 'Prenotata', blocked: 'Bloccata', availOverview: 'Panoramica Disponibilità Camere', free: 'Libera', occupied: 'Occupata', totalUnits: 'Unità Totali', bookedUnits: 'Prenotate', freeUnits: 'Libere',
    basePricing: 'Prezzi Base', dateRangeOverrides: 'Sovrapprezzi per Periodo', addOverride: 'Aggiungi Sovrapprezzo', noOverrides: 'Nessun sovrapprezzo impostato.', startDate: 'Data Inizio', endDate: 'Data Fine', overridePrice: 'Prezzo Override', labelOptional: 'Etichetta (opzionale)', period: 'Periodo', label: 'Etichetta', editPricing: 'Modifica Prezzi', updatePrice: 'Aggiorna Prezzo',
    staffMembers: 'membri del personale', addStaff: 'Aggiungi Personale', editStaff: 'Modifica Personale', staffName: 'Nome', role: 'Ruolo / Mansione', removeStaff: 'Rimuovere questo membro del personale?', updateStaff: 'Aggiorna Personale', noStaff: 'Nessun personale', noStaffDesc: 'Aggiungi membri del personale alla directory.',
    createInvoice: 'Crea Fattura', invoiceNumber: 'Fattura #', amount: 'Importo', reservation: 'Prenotazione', markSent: 'Segna Inviata', markPaid: 'Segna Pagata', download: 'Scarica PDF', sendEmail: 'Invia Email', selectReservation: 'Seleziona prenotazione', noInvoices: 'Nessuna fattura', noInvoicesDesc: 'Crea la prima fattura da una prenotazione.', invoiceDownloaded: 'Fattura scaricata', invoiceSent: 'Fattura inviata', sendingEmail: 'Invio...',
    hotelInfo: 'Informazioni Hotel', hotelName: 'Nome Hotel', logoUrl: 'URL Logo', address: 'Indirizzo', phone: 'Telefono', operations: 'Operazioni', currency: 'Valuta', checkInTime: 'Orario Check-In', checkOutTime: 'Orario Check-Out', taxPercentage: 'Percentuale Tasse', policies: 'Politiche', bookingPolicy: 'Politica di Prenotazione', cancellationPolicy: 'Politica di Cancellazione', language: 'Lingua', theme: 'Tema', light: 'Chiaro', dark: 'Scuro', system: 'Sistema', settingsSaved: 'Impostazioni salvate', saveSettings: 'Salva Impostazioni', appearance: 'Aspetto',
  },
};

const fr: typeof en = {
  nav: { rooms: 'Chambres', dining: 'Restaurant', amenities: 'Services', gallery: 'Galerie', about: 'À Propos', contact: 'Contact', reserveNow: 'Réserver' },
  hero: { subtitle: 'Hôtel & Resort de Luxe Cinq Étoiles', description: "Où l'élégance intemporelle rencontre le luxe moderne. Découvrez une hospitalité de classe mondiale, une cuisine étoilée Michelin et un service sur mesure au cœur de la Méditerranée.", bookStay: 'Réserver Votre Séjour', exploreRooms: 'Découvrir les Chambres' },
  rooms: { label: 'Hébergements', title: 'Chambres & Suites', description: 'Chaque chambre est un sanctuaire de goût raffiné, conçu pour les hôtes qui apprécient l\'extraordinaire.', reserveRoom: 'Réserver Cette Chambre', perNight: '/nuit', guests: 'Personnes', noRooms: 'Aucune chambre disponible pour le moment.' },
  footer: { tagline: "Luxe cinq étoiles sur la côte méditerranéenne. Où l'élégance intemporelle rencontre la sophistication moderne.", quickLinks: 'Liens Rapides', guestServices: 'Services Clients', bookRoom: 'Réserver une Chambre', restaurantRes: 'Réservation Restaurant', contactUs: 'Nous Contacter', contactLabel: 'Contact', privacy: 'Politique de Confidentialité', terms: 'Conditions Générales', cookies: 'Politique des Cookies', rights: '© 2026 Aurelia Grand. Tous droits réservés.' },
  booking: { title: 'Réserver Votre Séjour', subtitle: 'Sélectionnez votre chambre, vos dates et complétez votre réservation.', backHome: "Retour à l'Accueil", selectRoom: 'Sélectionner Chambre', checkInDate: "Date d'Arrivée", checkOutDate: 'Date de Départ', selectDate: 'Sélectionner date', numGuests: 'Nombre de Personnes', guest: 'Personne', guestsLabel: 'Personnes', roomDates: 'Chambre & Dates', guestDetails: 'Détails Client', checkingAvail: 'Vérification de disponibilité...', available: 'Disponible !', notAvailable: 'Non Disponible', notAvailableDesc: 'Ces dates ne sont pas disponibles. Veuillez essayer d\'autres dates.', continue: 'Continuer aux Détails', bookingSummary: 'Résumé de Réservation', night: 'nuit', nights: 'nuits', total: 'Total', fullName: 'Nom Complet', email: 'Email', phone: 'Téléphone', specialRequests: 'Demandes Spéciales', back: 'Retour', submit: 'Soumettre la Réservation', submitting: 'Envoi en cours...', submitted: 'Réservation Soumise', submittedThank: 'Merci ! Votre réservation a été reçue.', pendingNote: 'Statut : En attente — Nous confirmerons votre réservation sous 24 heures.', returnHome: "Retour à l'Accueil" },
  admin: {
    dashboard: 'Tableau de Bord', reservations: 'Réservations', roomTypes: 'Types de Chambre', availability: 'Disponibilité', pricing: 'Tarifs', staff: 'Personnel', invoices: 'Factures', settings: 'Paramètres', signOut: 'Déconnexion', adminPanel: 'Panneau Admin',
    save: 'Enregistrer', saving: 'Enregistrement...', cancel: 'Annuler', edit: 'Modifier', delete: 'Supprimer', create: 'Créer', search: 'Rechercher', actions: 'Actions', status: 'Statut', noData: 'Aucune donnée', confirm: 'Confirmer', active: 'Actif',
    loginTitle: 'Portail Admin', loginSubtitle: 'Connectez-vous pour gérer votre établissement', email: 'Email', password: 'Mot de passe', signIn: 'Se Connecter', signingIn: 'Connexion...',
    totalReservations: 'Total Réservations', pending: 'En Attente', revenueMonth: 'Revenus (Mois)', checkInsToday: "Arrivées Aujourd'hui", checkOutsToday: "Départs Aujourd'hui", occupancy: 'Occupation', bookingsOverview: 'Aperçu des Réservations', last6Months: '6 derniers mois', reservationStatus: 'Statut des Réservations', recentReservations: 'Réservations Récentes', viewAll: 'Voir Tout', guestsOverview: 'Aperçu des Clients', roomOccupancy: 'Occupation des Chambres', conflict: 'Conflit',
    upcomingArrivals: 'Arrivées Prochaines', upcomingDepartures: 'Départs Prochains', revenueToday: "Revenus Aujourd'hui", quickActions: 'Actions Rapides', addGuest: 'Ajouter Client', unconfirmedAlert: 'Réservations Non Confirmées', pendingReservationsAlert: 'réservations en attente nécessitent attention', bookingSourceBreakdown: 'Sources de Réservation', occupancyNext7Days: 'Occupation 7 Prochains Jours', todayTomorrow: "Aujourd'hui et Demain", website: 'Site Web', manual: 'Manuel', phone: 'Téléphone', direct: 'Direct', noPendingReservations: 'Aucune réservation en attente',
    searchGuests: 'Rechercher des clients...', allStatus: 'Tous les Statuts', confirmed: 'Confirmée', cancelled: 'Annulée', completed: 'Terminée', newReservation: 'Nouvelle Réservation', editReservation: 'Modifier Réservation', reservationDetails: 'Détails Réservation', code: 'Code', guest: 'Client', room: 'Chambre', checkIn: 'Arrivée', checkOut: 'Départ', guestName: 'Nom du Client', guestEmail: 'Email', guestPhone: 'Téléphone', guests: 'Personnes', totalPrice: 'Prix Total', specialRequests: 'Demandes Spéciales', notes: 'Notes', createReservation: 'Créer Réservation', creating: 'Création...', markCompleted: 'Marquer Terminée', saveChanges: 'Enregistrer', payment: 'Paiement', source: 'Source', roomType: 'Type de Chambre', selectRoom: 'Sélectionner chambre', noReservations: 'Aucune réservation', noReservationsDesc: 'Aucune réservation ne correspond aux filtres.',
    addRoomType: 'Ajouter Type', editRoomType: 'Modifier Type', newRoomType: 'Nouveau Type', roomName: 'Nom', description: 'Description', basePrice: 'Prix de Base', weekendPrice: 'Prix Weekend', maxGuests: 'Max Personnes', availableUnits: 'Unités Disponibles', roomSize: 'Taille', imageUrl: 'URL Image', amenitiesLabel: 'Équipements', showOnWebsite: 'Afficher sur le Site', showOnWebsiteDesc: 'Rendre cette chambre visible sur le site public', visibleOnWebsite: 'Visible sur le site', hiddenFromWebsite: 'Masquée du site', deleteRoomType: 'Supprimer ce type de chambre ?', units: 'unités', unit: 'unité', noRoomTypesTitle: 'Aucun type de chambre', noRoomTypesDesc: 'Ajoutez votre premier type de chambre.',
    selectRoomType: 'Sélectionner type de chambre', blockDates: 'Bloquer des Dates', noRoomTypesAvail: 'Aucun type de chambre', noRoomTypesAvailDesc: 'Créez des types de chambre pour gérer la disponibilité.', clickToBlock: 'Cliquez sur une date pour bloquer/débloquer', blockedDates: 'Dates Bloquées', noBlockedDates: 'Aucune date bloquée pour ce type de chambre.', blockDate: 'Bloquer Date', date: 'Date', reason: 'Raison', reserved: 'Réservée', blocked: 'Bloquée', availOverview: 'Aperçu Disponibilité Chambres', free: 'Libre', occupied: 'Occupée', totalUnits: 'Unités Totales', bookedUnits: 'Réservées', freeUnits: 'Libres',
    basePricing: 'Tarifs de Base', dateRangeOverrides: 'Tarifs Saisonniers', addOverride: 'Ajouter Tarif', noOverrides: 'Aucun tarif saisonnier défini.', startDate: 'Date Début', endDate: 'Date Fin', overridePrice: 'Prix Override', labelOptional: 'Libellé (optionnel)', period: 'Période', label: 'Libellé', editPricing: 'Modifier Tarifs', updatePrice: 'Mettre à Jour',
    staffMembers: 'membres du personnel', addStaff: 'Ajouter Personnel', editStaff: 'Modifier Personnel', staffName: 'Nom', role: 'Rôle / Poste', removeStaff: 'Supprimer ce membre du personnel ?', updateStaff: 'Mettre à Jour', noStaff: 'Aucun personnel', noStaffDesc: 'Ajoutez des membres du personnel.',
    createInvoice: 'Créer Facture', invoiceNumber: 'Facture #', amount: 'Montant', reservation: 'Réservation', markSent: 'Marquer Envoyée', markPaid: 'Marquer Payée', download: 'Télécharger PDF', sendEmail: 'Envoyer Email', selectReservation: 'Sélectionner réservation', noInvoices: 'Aucune facture', noInvoicesDesc: 'Créez votre première facture à partir d\'une réservation.', invoiceDownloaded: 'Facture téléchargée', invoiceSent: 'Facture envoyée', sendingEmail: 'Envoi...',
    hotelInfo: "Informations de l'Hôtel", hotelName: "Nom de l'Hôtel", logoUrl: 'URL du Logo', address: 'Adresse', phone: 'Téléphone', operations: 'Opérations', currency: 'Devise', checkInTime: "Heure d'Arrivée", checkOutTime: 'Heure de Départ', taxPercentage: 'Pourcentage Taxes', policies: 'Politiques', bookingPolicy: 'Politique de Réservation', cancellationPolicy: "Politique d'Annulation", language: 'Langue', theme: 'Thème', light: 'Clair', dark: 'Sombre', system: 'Système', settingsSaved: 'Paramètres enregistrés', saveSettings: 'Enregistrer', appearance: 'Apparence',
  },
};

export const translations: Record<Language, typeof en> = { en, it, fr };

export const languageNames: Record<Language, string> = { en: 'English', it: 'Italiano', fr: 'Français' };
