// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdxtmdyagsxtvtjaxqou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkeHRtZHlhZ3N4dHZ0amF4cW91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5Mjc1MDYsImV4cCI6MjA4ODUwMzUwNn0.HiJlhsguyFf11lKAVXi0hDEgUyvKyH-8kNhJBpVs_No";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});